import type { Metadata } from "next";
import "./globals.css";
import MasterLayout from "@/Layout/MasterLayout";
import "@fontsource/hind-siliguri"; // Defaults to weight 400
import "@fontsource/hind-siliguri/400.css"; // Specify weight



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MasterLayout>
          <div>
             {children}
          </div>
        </MasterLayout>
      </body>
    </html>
  );
}
